POST http://localhost:8080/api/carts/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjk2MTI2Y2MzMjYyN2FiYzNhZTVmMyIsImVtYWlsIjoiYXJpYW5mZXJuYW5kZXpAZ21haWwuY29tIiwiaWF0IjoxNjQzODk3NjQxfQ.66GcJ_hywv-BHsLRmJPgxrCQpm7FEh6zEPusP4U-LfA

{
  "productId": "61f9700e96edb5e34a2f1c2c",
  "addCount": 2
}