PUT http://localhost:8080/api/products
Content-Type: application/json

{
  "productId": "61f9d793b5f5b93fb6837624",
  "newProduct" : {
    "title": "LISTERINE - Enjuague bucal",
    "price": 490,
    "thumbnail": "https://jumboargentina.vtexassets.com/arquivos/ids/439627-800-600?v=636517679773430000&width=800&height=600&aspect=true"
  }
}